### ISSUE TITLE
minecraft server is dead when over 45 minute

### ISSUE THREAD

**Issue by Castar** [overshard/docker-minecraft#14]
Im using CoreOS on Microsoft Azure.
But.. I Can't run my minecraft server because minecraft server is dead when over 45 minute..
i believe you can fix.. thanks :D

**Comment by overshard** [comment]
This isn't something I can fix and we aren't really supporting CoreOS right now, I need to look into it but how we store files so they can be backed up doesn't work with CoreOS.
