### ISSUE TITLE
Is there any way to send server commands?

### ISSUE THREAD

**Issue by thestonefox** [overshard/docker-minecraft#2]
Hi,

As this just runs as a supervisord process, is there any way to send the minecraft server commands (such as "say")

I can get onto the server using nsenter but as it's just the process running, I don't see how to send a command.

**Comment by tbsalling** [comment]
If you have launched the Minecraft server with "docker run -it ...", then you can later use "docker attach" to attach to the server and then issue Minecraft server commands from there.
