### ISSUE TITLE
Specify the version at the time of boot.

### ISSUE THREAD

**Issue by kuniiskywalker** [overshard/docker-minecraft#23]
I would like to be able to switch versions at run time to make the update easier.
I think that it is better to execute it as follows.

`docker run -e VERSION=1.9.4 -d minecraft-docker`

**Comment by overshard** [comment]
I don't plan on updating this project anymore since docker has changed dramatically this would need a complete rewrite, closing this, if someone wants to provide a better alternative I'd be happy to link to it.
